#!/usr/bin/env bash
if [ $# -ne 2 ]; then
	echo "Usage: section <set1> <set2> - Calculates the intersection between two sets." 
	exit 1 
fi
if [ ! -f $1 ]; then 
	echo "Error: The set '$1' does not exist."
	echo "Usage: section <set1> <set2> - Calculates the intersection between two sets." 
	exit 1
fi
if [ ! -f $2 ]; then						  
  	echo "Error: The set '$2' does not exist."		
	echo "Usage: section <set1> <set2> - Calculates the intersection between two sets." 
	exit 1
fi
cat $1 $2 | sort | uniq -c | grep "^ *2" | sed "s/^ *2 //"
