#!/usr/bin/env bash
if [ $# -ne 2 ]; then
	echo "Usage: union <set1> <set2> - Calculates the union of two sets."
	exit 1
fi
if [ ! -f $1 ]; then
	echo "Error: The set '$1' does not exist."
	echo "Usage: union <set1> <set2> - Calculates the union of two sets."
	exit 1
fi
if [ ! -f $2 ]; then
	echo "Error: The set '$2' does not exist."
	echo "Usage: union <set1> <set2> - Calculates the union of two sets."
	exit 1
fi
cat $1 $2 | sort | uniq
