#!/usr/bin/env bash
if [ $# -eq 0 ]; then
	echo "Usage: section <set1> ... - Calculates the intersection of one or more sets."
	exit 1
fi
if [ ! -f $1 ]; then
	echo "Error: The set '$1' does not exist."
	echo "Usage: msection <set1> ... - Calculates the intersection of one or more sets."
	exit 1
fi
if [ $# -eq 1 ]; then
	cat $1
elif [ $# -eq 2 ]; then
	./section $1 $2
else
	arghead="$1"
	argtail=`mktemp .XXXXXXXXXX`
	shift
        ./msection "$@" > $argtail
	./section $arghead $argtail
	rm -f $argtail
fi


